apply plugin: 'com.android.application'

android {
    compileSdk 35

    defaultConfig {
        applicationId "org.literacyapp.handwriting"
        minSdk 26
        targetSdk 35
        versionCode 1000002
        versionName "1.0.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            buildConfigField "String", "CONTENT_PROVIDER_APPLICATION_ID", '"ai.elimu.content_provider.debug"'
        }
        release {
            minifyEnabled false
            buildConfigField "String", "CONTENT_PROVIDER_APPLICATION_ID", '"ai.elimu.content_provider"'
        }
    }

    buildFeatures {
        buildConfig true
    }

    lintOptions {
        abortOnError false
    }

    namespace "org.literacyapp.handwriting"
}

repositories {
    mavenLocal()
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.6.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation 'ai.elimu:content-provider:1.4.38'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'org.encog:encog-core:3.1.0'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    testImplementation 'junit:junit:4.12'
}
