plugins {
    alias(libs.plugins.android.application)
}

android {
    compileSdk 35

    defaultConfig {
        applicationId "org.literacyapp.handwriting"
        minSdk 26
        targetSdk 35
        versionCode 1000002
        versionName "1.0.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            buildConfigField "String", "CONTENT_PROVIDER_APPLICATION_ID", '"ai.elimu.content_provider.debug"'
        }
        release {
            minifyEnabled false
            buildConfigField "String", "CONTENT_PROVIDER_APPLICATION_ID", '"ai.elimu.content_provider"'
        }
    }

    buildFeatures {
        buildConfig true
    }

    lintOptions {
        abortOnError false
    }

    namespace "org.literacyapp.handwriting"
}

repositories {
    mavenLocal()
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation(libs.androidx.test.espresso.core) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }

    implementation libs.elimu.content.provider
    implementation libs.androidx.appcompat
    implementation libs.androidx.cardview
    implementation libs.androidx.legacy.support.v4
    implementation libs.encog.core
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.runner
    testImplementation libs.junit
}
